### ISSUE TITLE
charset probleem

### ISSUE THREAD

**Issue by Krinkle** [wmnl/wikipedia-portals#15]
https://www.wikipedia.nl/archive/nl.html

<img width="511" alt="Screenshot 2022-07-26 at 21 03 53" src="https://user-images.githubusercontent.com/156867/181158364-4958117b-4788-43de-8c96-f48314edfa1f.png">

**Comment by hay** [comment]
Yes, that is to be expected. This is an older version of the homepage that is purely kept for archival purposes. It's no longer maintained and bugs there will not be fixed.

**Comment by Krinkle** [comment]
@hay I understand we're not meant to improve it, but I believe this defect was introduced when the homepage was copied to the new server and/or into source control by mixing up the charset somewhere. When viewing archive.org or the screenshot at [T139051](https://phabricator.wikimedia.org/T139051), the text was not corrupted before.

**Comment by hay** [comment]
@Krinkle hmm... seems the files in the repo are fine (i don't see the mojibake there), so maybe you're right and the problem is on the server. I don't have any access to that specific server so it would be a bit of a hassle to fix it just for archival purposes.
